/*
 *     Generated by class-dump 3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#pragma mark Named Structures

//struct CGPoint {
//    double x;
//    double y;
//};
//
//struct CGRect {
//    struct CGPoint origin;
//    struct CGSize size;
//};
//
//struct CGSize {
//    double width;
//    double height;
//};

#pragma mark -

/*
 * File: /System/Library/PrivateFrameworks/SystemUIPlugin.framework/Versions/A/SystemUIPlugin
 * Arch: Intel x86-64 (x86_64)
 *       Current version: 2.0.0, Compatibility version: 1.0.0
 *
 *       Objective-C Garbage Collection: Unsupported
 */

@interface NSMenuExtra : NSStatusItem
{
    NSBundle *_bundle;
    NSMenu *_menu;
    NSView *_view;
    double _length;
    struct {
        unsigned int customView:1;
        unsigned int menuDown:1;
        unsigned int reserved:30;
    } _flags;
    id _controller;
    BOOL _supportsAnimation;
    NSArray *_animatedImages;
    double _imageFrameRate;
    double _maxWidth;
}

+ (unsigned int)defaultLength;
- (id)initWithBundle:(id)arg1;
- (id)initWithBundle:(id)arg1 data:(id)arg2;
- (void)willUnload;
- (void)dealloc;
- (id)bundle;
- (double)length;
- (void)setLength:(double)arg1;
- (id)image;
- (void)setImage:(id)arg1;
- (id)alternateImage;
- (void)setAlternateImage:(id)arg1;
- (id)menu;
- (void)setMenu:(id)arg1;
- (id)toolTip;
- (void)setToolTip:(id)arg1;
- (id)view;
- (void)setView:(id)arg1;
- (BOOL)convertedForNewUI;
- (BOOL)isMenuDown;
- (BOOL)isMenuDownForAX;
- (void)drawMenuBackground:(BOOL)arg1;
- (void)popUpMenu:(id)arg1;
- (void)unload;
- (id)statusBar;
- (SEL)action;
- (void)setAction:(SEL)arg1;
- (id)target;
- (void)setTarget:(id)arg1;
- (id)title;
- (void)setTitle:(id)arg1;
- (id)attributedTitle;
- (void)setAttributedTitle:(id)arg1;
- (BOOL)isEnabled;
- (void)setEnabled:(BOOL)arg1;
- (void)setHighlightMode:(BOOL)arg1;
- (BOOL)highlightMode;
- (long long)sendActionOn:(long long)arg1;
- (id)_initInStatusBar:(id)arg1 withLength:(float)arg2 withPriority:(int)arg3;
- (id)_window;
- (id)_button;
- (void)_adjustLength;
@property(nonatomic) double imageFrameRate;
@property(nonatomic) double maxWidth;
@property(copy, nonatomic) NSArray *images;
- (void)setAnimationText:(id)arg1;
- (void)setStaticText:(id)arg1;
- (void)startImageAnimation;
- (void)stopImageAnimation;
- (void)startTextAnimation;
- (void)stopTextAnimation;
- (void)setsSupportsAnimation:(BOOL)arg1;
- (void)setController:(id)arg1;
- (id)controller;
- (void)setMenuDown:(BOOL)arg1;
- (double)defaultLength;
- (id)accessibilityAttributeNames;
- (id)accessibilityAttributeValue:(id)arg1;
- (BOOL)accessibilityIsAttributeSettable:(id)arg1;
- (void)accessibilitySetValue:(id)arg1 forAttribute:(id)arg2;
- (id)accessibilityActionNames;
- (id)accessibilityActionDescription:(id)arg1;
- (void)accessibilityPerformAction:(id)arg1;
- (BOOL)accessibilityIsIgnored;
- (id)accessibilityHitTest:(struct CGPoint)arg1;
- (id)accessibilityFocusedUIElement;
- (id)AXRole;
- (id)AXRoleDescription;
- (id)AXSubrole;
- (id)AXDescription;
- (id)AXChildren;
- (id)AXParent;
- (id)AXTitle;
- (id)AXValue;
- (id)AXEnabled;
- (id)AXSelected;
- (BOOL)isAXSelectedSettable;
- (void)setAXSelected:(id)arg1;
- (id)AXPosition;
- (id)AXSize;
- (void)performAXPress;
- (void)performAXCancel;
@property(nonatomic) BOOL supportsAnimation; // @synthesize supportsAnimation=_supportsAnimation;

@end

@interface NSMenuExtraView : NSView
{
    NSMenu *_menu;
    NSMenuExtra *_menuExtra;
    NSImage *_image;
    NSImage *_alternateImage;
}

- (id)initWithFrame:(NSRect)arg1 menuExtra:(id)arg2;
- (void)dealloc;
- (void)setMenu:(id)arg1;
- (id)image;
- (void)setImage:(id)arg1;
- (id)alternateImage;
- (void)setAlternateImage:(id)arg1;
- (void)drawRect:(NSRect)arg1;
- (void)mouseDown:(id)arg1;

@end

@interface DockExtra : NSObject
{
    id _private;
}

- (id)_initWithController:(id)arg1;
- (void)dealloc;
- (void)invalidate;
- (id)getContext:(struct CGSize *)arg1;
- (BOOL)setDockImageFromContext;
- (void)releaseContext;
- (BOOL)resetDockImage;
- (id)_controller;

@end

@interface NSMenuExtraAnimationView : NSView
{
    NSMenuExtra *_menuExtra;
    NSArray *_images;
    NSArray *_alternateImages;
    unsigned long long _imageFrame;
    double _imageFrameRate;
    NSTimer *_updateImageTimer;
    NSImage *_textImage;
    NSImage *_textImageHighlighted;
    unsigned long long _textImageFrame;
    unsigned long long _maxTextImageFrame;
    int _textStage;
    NSTimer *_updateTextTimer;
    struct CGRect _minFrame;
    double _maxWidth;
    double _widthIncrement;
    NSImageCell *_imageCell;
}

- (id)_imageFromText:(id)arg1 highlighted:(BOOL)arg2;
- (id)_textAttributes:(BOOL)arg1;
- (void)_updateTextAnimation:(id)arg1;
- (void)_updateImageAnimation:(id)arg1;
- (id)_getImageArray;
@property(nonatomic) double maxWidth; // @synthesize maxWidth=_maxWidth;
@property(nonatomic) double imageFrameRate; // @synthesize imageFrameRate=_imageFrameRate;
- (void)startImageAnimation;
- (void)stopImageAnimation;
- (void)setStaticText:(id)arg1;
- (void)setAnimationText:(id)arg1;
- (void)startTextAnimation;
- (void)stopTextAnimation;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 menuExtra:(id)arg2;
- (void)dealloc;
@property(assign, nonatomic) NSMenuExtra *menuExtra; // @synthesize menuExtra=_menuExtra;
@property(copy, nonatomic) NSArray *alternateImages; // @synthesize alternateImages=_alternateImages;
@property(copy, nonatomic) NSArray *images; // @synthesize images=_images;

@end

